// <auto-generated />
namespace Rosond_Web_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixCascadePaths : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCascadePaths));
        
        string IMigrationMetadata.Id
        {
            get { return "202507090505054_FixCascadePaths"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
